"""add_analysis_data

Revision ID: 0e5ab26f3a6b
Revises: 36cf823dcdfc
Create Date: 2026-04-01 18:19:17.392627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e5ab26f3a6b'
down_revision = '36cf823dcdfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demands')
    with op.batch_alter_table('group_purchase_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uk_group_participant'))

    op.drop_table('group_purchase_participants')
    op.drop_table('supplier_display_controls')
    with op.batch_alter_table('collaboration_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('code'))

    op.drop_table('collaboration_codes')
    op.drop_table('order_financing_applications')
    op.drop_table('group_purchases')
    op.drop_table('code_verification_logs')
    op.drop_table('fulfillment_data')
    op.drop_table('report_records')
    op.drop_table('alert_workflows')
    with op.batch_alter_table('industrial_commerce_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('query_key'))

    op.drop_table('industrial_commerce_cache')
    op.drop_table('lead_onboarding_applications')
    op.drop_table('quality_labels')
    op.drop_table('operation_logs')
    op.drop_table('enterprise_patents')
    with op.batch_alter_table('alert_thresholds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('dimension'))

    op.drop_table('alert_thresholds')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('key_value'))

    op.drop_table('api_keys')
    with op.batch_alter_table('product_import_risks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('product_name'))

    op.drop_table('product_import_risks')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('order_no'))

    op.drop_table('orders')
    with op.batch_alter_table('data_authorizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uk_ent_data_type'))

    op.drop_table('data_authorizations')
    with op.batch_alter_table('external_interface_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('interface_type'))

    op.drop_table('external_interface_configs')
    op.drop_table('case_library')
    op.drop_table('credit_rules')
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.alter_column('poster_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('buyer_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('seller_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
        batch_op.create_foreign_key(None, 'enterprises', ['poster_id'], ['id'])
        batch_op.drop_column('is_anonymous')
        batch_op.drop_column('source')
        batch_op.drop_column('is_group_purchase')
        batch_op.drop_column('group_purchase_id')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['match_code'])
        batch_op.create_foreign_key(None, 'inquiries', ['inquiry_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_purchase_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_group_purchase', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('source', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), server_default=sa.text("'manual'"), nullable=False))
        batch_op.add_column(sa.Column('is_anonymous', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('seller_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('buyer_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('poster_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    op.create_table('credit_rules',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rule_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('score_change', mysql.FLOAT(), nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('max_per_month', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('change_reason', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('case_library',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('buyer_name_masked', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('product_category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('cooperation_time', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('amount_range', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('is_public', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('display_order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['enterprises.id'], name=op.f('case_library_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('external_interface_configs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('interface_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('interface_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('base_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('auth_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=True),
    sa.Column('api_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('client_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('client_secret', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('timeout_seconds', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_retries', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('field_mapping', mysql.JSON(), nullable=True),
    sa.Column('is_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('last_check_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('last_check_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_check_error', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('external_interface_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('interface_type'), ['interface_type'], unique=True)

    op.create_table('data_authorizations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('enterprise_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('authorized', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('authorized_at', mysql.DATETIME(), nullable=True),
    sa.Column('revoked_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_sync_at', mysql.DATETIME(), nullable=True),
    sa.Column('sync_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('error_message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('data_authorizations_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('data_authorizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uk_ent_data_type'), ['enterprise_id', 'data_type'], unique=True)

    op.create_table('orders',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_no', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('enterprise_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('customer_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('order_date', sa.DATE(), nullable=False),
    sa.Column('delivery_date', sa.DATE(), nullable=True),
    sa.Column('actual_delivery_date', sa.DATE(), nullable=True),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('orders_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('order_no'), ['order_no'], unique=True)

    op.create_table('product_import_risks',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('import_ratio', mysql.FLOAT(), nullable=False),
    sa.Column('source_countries', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('hs_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('data_source', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('product_import_risks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('product_name'), ['product_name'], unique=True)

    op.create_table('api_keys',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key_value', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('key_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('organization', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('permissions', mysql.JSON(), nullable=True),
    sa.Column('rate_limit', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_used_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('key_value'), ['key_value'], unique=True)

    op.create_table('alert_thresholds',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dimension', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=False),
    sa.Column('threshold_value', mysql.FLOAT(), nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('alert_thresholds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('dimension'), ['dimension'], unique=True)

    op.create_table('enterprise_patents',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('enterprise_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('patent_no', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('patent_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('ipc_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('apply_date', sa.DATE(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('enterprise_patents_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('operation_logs',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_role', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('operation_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('operation_target', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('target_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('operation_detail', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True),
    sa.Column('user_agent', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('result', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('error_message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['enterprises.id'], name=op.f('operation_logs_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('quality_labels',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('enterprise_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('label_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('issuer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('certificate_no', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('valid_from', sa.DATE(), nullable=True),
    sa.Column('valid_until', sa.DATE(), nullable=True),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('quality_labels_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issuer_id'], ['enterprises.id'], name=op.f('quality_labels_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('lead_onboarding_applications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('enterprise_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qualification_docs', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('supplier_management_system', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('supplier_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('annual_procurement', mysql.FLOAT(), nullable=True),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('submitted_at', mysql.DATETIME(), nullable=True),
    sa.Column('reviewed_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', mysql.DATETIME(), nullable=True),
    sa.Column('review_notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('lead_onboarding_applications_ibfk_1')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['enterprises.id'], name=op.f('lead_onboarding_applications_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('industrial_commerce_cache',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('query_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('result_data', mysql.JSON(), nullable=True),
    sa.Column('cached_at', mysql.DATETIME(), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('industrial_commerce_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('query_key'), ['query_key'], unique=True)

    op.create_table('alert_workflows',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alert_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_to', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assigned_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assigned_at', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('handling_notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('evidence_urls', mysql.JSON(), nullable=True),
    sa.Column('completed_at', mysql.DATETIME(), nullable=True),
    sa.Column('reviewed_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('review_result', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('review_notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('alert_workflows_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_by'], ['enterprises.id'], name=op.f('alert_workflows_ibfk_3')),
    sa.ForeignKeyConstraint(['assigned_to'], ['enterprises.id'], name=op.f('alert_workflows_ibfk_2')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['enterprises.id'], name=op.f('alert_workflows_ibfk_4')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('report_records',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reporter_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reported_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('report_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('target_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('target_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('evidence_urls', mysql.JSON(), nullable=True),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('handler_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('handling_notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('handled_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['handler_id'], ['enterprises.id'], name=op.f('report_records_ibfk_3')),
    sa.ForeignKeyConstraint(['reported_id'], ['enterprises.id'], name=op.f('report_records_ibfk_2')),
    sa.ForeignKeyConstraint(['reporter_id'], ['enterprises.id'], name=op.f('report_records_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('fulfillment_data',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('collaboration_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('invoice_no', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('invoice_amount', mysql.FLOAT(), nullable=True),
    sa.Column('invoice_date', sa.DATE(), nullable=True),
    sa.Column('delivery_date', sa.DATE(), nullable=True),
    sa.Column('on_time', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('quality_rating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('buyer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seller_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['enterprises.id'], name=op.f('fulfillment_data_ibfk_1')),
    sa.ForeignKeyConstraint(['seller_id'], ['enterprises.id'], name=op.f('fulfillment_data_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('code_verification_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('caller_api_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True),
    sa.Column('caller_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True),
    sa.Column('result', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('group_purchases',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('initiator_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('target_quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('participant_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_credit_score', mysql.FLOAT(), nullable=True),
    sa.Column('deadline', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['initiator_id'], ['enterprises.id'], name=op.f('group_purchases_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('order_financing_applications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('enterprise_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bank_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80), nullable=False),
    sa.Column('product_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80), nullable=False),
    sa.Column('loan_amount_yuan', mysql.FLOAT(), nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('order_financing_applications_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['enterprises.id'], name=op.f('order_financing_applications_ibfk_2'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('collaboration_codes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('buyer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seller_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contract_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('product_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('amount_range', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('fulfillment_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('valid_until', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['enterprises.id'], name=op.f('collaboration_codes_ibfk_1')),
    sa.ForeignKeyConstraint(['seller_id'], ['enterprises.id'], name=op.f('collaboration_codes_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('collaboration_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('code'), ['code'], unique=True)

    op.create_table('supplier_display_controls',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lead_enterprise_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('display_mode', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('authorized', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('authorized_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['lead_enterprise_id'], ['enterprises.id'], name=op.f('supplier_display_controls_ibfk_1')),
    sa.ForeignKeyConstraint(['supplier_id'], ['enterprises.id'], name=op.f('supplier_display_controls_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('group_purchase_participants',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_purchase_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('participant_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('joined_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['group_purchase_id'], ['group_purchases.id'], name=op.f('group_purchase_participants_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['enterprises.id'], name=op.f('group_purchase_participants_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('group_purchase_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uk_group_participant'), ['group_purchase_id', 'participant_id'], unique=True)

    op.create_table('demands',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', mysql.ENUM('supply', 'demand'), nullable=False),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('enterprise_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('demands_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('demands_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
