"""add wechat related columns

Revision ID: 36cf823dcdfc
Revises: db3c090a6f67
Create Date: 2026-03-28 23:34:34.563297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36cf823dcdfc'
down_revision = 'db3c090a6f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # MySQL: indexes used by FKs cannot be dropped before the table; drop the table directly.
    op.execute(sa.text("SET FOREIGN_KEY_CHECKS=0"))
    op.execute(sa.text("DROP TABLE IF EXISTS industry_chain_relations"))
    op.execute(sa.text("SET FOREIGN_KEY_CHECKS=1"))
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.alter_column('auto_pushed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.create_foreign_key(None, 'recruitment_tasks', ['linked_recruitment_task_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('enterprises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wechat_bound', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('wechat_work_userid', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('wechat_work_openid', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('wechat_service_openid', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('wechat_bound_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('wechat_push_preference', sa.String(length=20), nullable=True))
        batch_op.alter_column('daily_quote_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('daily_quote_limit',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'3'"))
        batch_op.alter_column('is_lead_enterprise',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('data_freshness_score',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'100'"))
        batch_op.alter_column('is_dormant',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('current_mode',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               nullable=True,
               existing_server_default=sa.text("'buyer'"))
        batch_op.drop_column('llm_tags')

    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.drop_column('group_purchase_id')
        batch_op.drop_column('is_group_purchase')
        batch_op.drop_column('source')
        batch_op.drop_column('is_anonymous')

    with op.batch_alter_table('match_feedbacks', schema=None) as batch_op:
        batch_op.alter_column('rl_reward_applied',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_feedbacks', schema=None) as batch_op:
        batch_op.alter_column('rl_reward_applied',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_anonymous', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('source', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), server_default=sa.text("'manual'"), nullable=False))
        batch_op.add_column(sa.Column('is_group_purchase', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('group_purchase_id', mysql.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('enterprises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_tags', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='存储LLM抽取的标签JSON'))
        batch_op.alter_column('current_mode',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               nullable=False,
               existing_server_default=sa.text("'buyer'"))
        batch_op.alter_column('is_dormant',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('data_freshness_score',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'100'"))
        batch_op.alter_column('is_lead_enterprise',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('daily_quote_limit',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'3'"))
        batch_op.alter_column('daily_quote_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_column('wechat_push_preference')
        batch_op.drop_column('wechat_bound_at')
        batch_op.drop_column('wechat_service_openid')
        batch_op.drop_column('wechat_work_openid')
        batch_op.drop_column('wechat_work_userid')
        batch_op.drop_column('wechat_bound')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('auto_pushed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    op.create_table('industry_chain_relations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('upstream_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('downstream_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('relation_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=False),
    sa.Column('strength', mysql.FLOAT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['downstream_id'], ['enterprises.id'], name=op.f('industry_chain_relations_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upstream_id'], ['enterprises.id'], name=op.f('industry_chain_relations_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('industry_chain_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_chain_relation'), ['upstream_id', 'downstream_id', 'relation_type'], unique=True)
        batch_op.create_index(batch_op.f('ix_industry_chain_relations_upstream_id'), ['upstream_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_industry_chain_relations_downstream_id'), ['downstream_id'], unique=False)

    # ### end Alembic commands ###
