"""initial_schema_all_tables

Revision ID: db3c090a6f67
Revises: 
Create Date: 2026-03-27 17:40:42.072202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db3c090a6f67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('industry_chain_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_industry_chain_relations_downstream_id'))
        batch_op.drop_index(batch_op.f('ix_industry_chain_relations_upstream_id'))
        batch_op.drop_index(batch_op.f('uq_chain_relation'))

    op.drop_table('industry_chain_relations')
    with op.batch_alter_table('enterprises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_quote_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('daily_quote_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_quote_reset_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('is_lead_enterprise', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_freshness_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_data_update', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_dormant', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('current_mode', sa.String(length=10), nullable=True))
        batch_op.drop_column('llm_tags')

    with op.batch_alter_table('match_feedbacks', schema=None) as batch_op:
        batch_op.alter_column('rl_reward_applied',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_feedbacks', schema=None) as batch_op:
        batch_op.alter_column('rl_reward_applied',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('enterprises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_tags', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='存储LLM抽取的标签JSON'))
        batch_op.drop_column('current_mode')
        batch_op.drop_column('is_dormant')
        batch_op.drop_column('last_data_update')
        batch_op.drop_column('data_freshness_score')
        batch_op.drop_column('is_lead_enterprise')
        batch_op.drop_column('last_quote_reset_date')
        batch_op.drop_column('daily_quote_limit')
        batch_op.drop_column('daily_quote_count')

    op.create_table('industry_chain_relations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('upstream_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('downstream_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('relation_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=False),
    sa.Column('strength', mysql.FLOAT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['downstream_id'], ['enterprises.id'], name=op.f('industry_chain_relations_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upstream_id'], ['enterprises.id'], name=op.f('industry_chain_relations_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('industry_chain_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_chain_relation'), ['upstream_id', 'downstream_id', 'relation_type'], unique=True)
        batch_op.create_index(batch_op.f('ix_industry_chain_relations_upstream_id'), ['upstream_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_industry_chain_relations_downstream_id'), ['downstream_id'], unique=False)

    # ### end Alembic commands ###
