import { useEffect, useState } from 'react';
import { ArrowRight, Bot, CheckCircle2, Download, ExternalLink, FileCheck2, Globe2, Info, Loader2, Network, PackageSearch, PhoneCall, Search, Target, Wrench, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { api, type PublicAgentMarketResponse } from '@/src/services/api';
import { useAuth } from '@/src/context/AuthContext';
import { PublicSiteHeader } from '@/src/components/PublicSiteHeader';

const ICONS = [Target, PackageSearch, Network, Wrench, FileCheck2, Globe2, Search];

export default function AgentMarket() {
  const navigate = useNavigate();
  const { requestLogin } = useAuth();
  const [market, setMarket] = useState<PublicAgentMarketResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [selectedSkill, setSelectedSkill] = useState<PublicAgentMarketResponse['groups'][number]['skills'][number] | null>(null);

  const loadMarket = async () => {
    setLoading(true);
    try { setMarket(await api.fetchPublicAgentMarket()); } catch { setError('Agent 能力目录暂时无法加载，请稍后重试'); } finally { setLoading(false); }
  };
  useEffect(() => { void loadMarket(); }, []);

  const downloadSkill = (skill: PublicAgentMarketResponse['groups'][number]['skills'][number]) => {
    const link = document.createElement('a');
    link.href = skill.download_url;
    link.download = `${skill.repo.split('/')[1]}-${skill.branch}.zip`;
    link.target = '_blank';
    link.rel = 'noreferrer';
    document.body.appendChild(link);
    link.click();
    link.remove();
    setSelectedSkill(skill);
  };

  return <div className="public-site min-h-screen bg-public-bg text-public-text"><PublicSiteHeader onLogin={() => requestLogin('/agent-market')} /><main className="mx-auto max-w-[1240px] px-4 py-10 md:px-8 md:py-16">
    <section className="grid gap-10 lg:grid-cols-[1fr_0.8fr] lg:items-center"><div><p className="eyebrow text-public-brand">AI capability market</p><h1 className="mt-4 text-4xl font-black leading-tight md:text-6xl">把 AI 放进真实的制造业务里</h1><p className="mt-5 max-w-xl text-base leading-7 text-public-muted">链易配围绕销售、采购、计划、生产、财法务、出海和产业情报，提供可以接入企业数据的岗位型 AI 能力。</p><div className="mt-7 flex flex-wrap gap-3"><button type="button" onClick={() => navigate('/aia')} className="btn-public-primary">先试用 AI 找工厂 <ArrowRight className="h-4 w-4" /></button><button type="button" onClick={() => requestLogin('/agent-market')} className="btn-public-secondary">预约业务诊断</button></div></div><div className="rounded-xl border border-public-border bg-public-surface p-6 shadow-public"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-lg bg-public-brand text-white"><Bot className="h-6 w-6" /></span><div><p className="text-xs font-bold text-public-brand">链小易 Agent 编队</p><h2 className="font-black">从数据到行动结果</h2></div></div><div className="mt-6 space-y-3">{(market?.layers || [{ title: '产业数据底座', description: '企业、产品、产能、信用和产业关系' }, { title: '企业业务数据', description: '订单、库存、BOM、客户和报价' }, { title: '岗位型 AI Agent', description: '名单、询价单、排产建议和风险告警' }]).map((layer, index) => <div key={layer.title} className="flex items-center gap-3 rounded-lg bg-public-bg p-3"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-public-brand-soft text-xs font-black text-public-brand">{index + 1}</span><div><p className="text-sm font-bold">{layer.title}</p><p className="mt-1 text-xs text-public-muted">{layer.description}</p></div></div>)}</div></div></section>
    {error && <div className="mt-8 flex items-center justify-between gap-3 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><span>{error}</span><button type="button" onClick={() => { setError(''); void loadMarket(); }} className="font-bold">重试</button></div>}
    <section className="mt-16"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow text-public-brand">Role-based agents</p><h2 className="mt-2 text-2xl font-black">按岗位选择 AI 能力</h2></div><span className="text-xs text-public-muted">能力卡片已关联 GitHub skill，可下载后接入你的 Agent</span></div>{loading ? <div className="mt-6 flex min-h-40 items-center justify-center gap-2 rounded-xl border border-public-border bg-public-surface text-sm text-public-muted"><Loader2 className="h-5 w-5 animate-spin" />正在加载能力目录…</div> : market?.groups.length ? <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{market.groups.map((group, index) => { const Icon = ICONS[index % ICONS.length]; return <article key={group.title} className="group rounded-xl border border-public-border bg-public-surface p-5 shadow-public transition hover:-translate-y-0.5 hover:border-public-brand/50"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-public-brand-soft text-public-brand"><Icon className="h-5 w-5" /></span>{group.demo ? <span className="badge badge-success">可演示</span> : <span className="badge badge-default">规划能力</span>}</div><h3 className="mt-5 text-lg font-black">{group.title}</h3><p className="mt-1 text-sm text-public-muted">{group.summary}</p><div className="mt-4 space-y-2">{group.agents.map(agent => <div key={agent} className="flex items-center gap-2 text-xs text-public-muted"><CheckCircle2 className="h-3.5 w-3.5 text-emerald-600" />{agent}</div>)}</div><div className="mt-5 border-t border-public-border pt-4"><p className="mb-2 flex items-center gap-1 text-[11px] font-bold uppercase tracking-wide text-public-muted"><Download className="h-3.5 w-3.5" />推荐 GitHub skills</p><div className="space-y-2">{group.skills.map(skill => <div key={skill.name} className="flex items-center justify-between gap-2 rounded-lg bg-public-bg px-3 py-2"><div className="min-w-0"><p className="truncate text-xs font-bold">{skill.label}</p><p className="truncate text-[10px] text-public-muted">{skill.purpose}</p></div><button type="button" onClick={() => downloadSkill(skill)} className="inline-flex shrink-0 items-center gap-1 rounded-md bg-public-brand px-2.5 py-1.5 text-[11px] font-bold text-white transition hover:opacity-90" aria-label={`下载 ${skill.label}`}><Download className="h-3 w-3" />下载</button></div>)}</div></div><button type="button" onClick={() => group.demo ? navigate('/aia') : requestLogin(`/agent-market?agent=${encodeURIComponent(group.title)}`)} className="mt-5 inline-flex items-center gap-1 text-xs font-bold text-public-brand">{group.demo ? '打开体验' : '预约配置'} <ArrowRight className="h-3.5 w-3.5 transition group-hover:translate-x-1" /></button></article>; })}</div> : <div className="mt-6 rounded-xl border border-dashed border-public-border bg-public-surface px-6 py-12 text-center text-sm text-public-muted">暂无可展示的 Agent 能力，请稍后重试。</div>}</section>
    <section className="mt-16 rounded-xl bg-public-brand p-7 text-white md:p-10"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-white/70">Start with one workflow</p><h2 className="mt-2 text-2xl font-black">先找到最值得交给 AI 的一件事</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/80">从一次真实询价或供应商寻源开始，明确数据、验收指标和实施边界，再逐步扩展到其他岗位。</p></div><button type="button" onClick={() => requestLogin('/agent-market')} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-lg bg-white px-5 py-3 text-sm font-bold text-public-brand">预约业务诊断 <PhoneCall className="h-4 w-4" /></button></div></section>
  </main>{selectedSkill && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" role="dialog" aria-modal="true" aria-labelledby="skill-dialog-title"><div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-public-surface p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wide text-public-brand">Skill 已开始下载</p><h2 id="skill-dialog-title" className="mt-1 text-xl font-black">{selectedSkill.label}</h2></div><button type="button" onClick={() => setSelectedSkill(null)} className="rounded-lg p-2 text-public-muted hover:bg-public-bg" aria-label="关闭"><X className="h-5 w-5" /></button></div><div className="mt-5 rounded-xl bg-public-bg p-4"><p className="flex items-center gap-2 text-sm font-bold"><Info className="h-4 w-4 text-public-brand" />如何使用</p><ol className="mt-3 space-y-2 text-sm leading-6 text-public-muted">{selectedSkill.usage.map((step, index) => <li key={step} className="flex gap-2"><span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-public-brand text-xs font-bold text-white">{index + 1}</span><span>{step}</span></li>)}</ol></div><div className="mt-4 flex flex-wrap items-center gap-3 text-xs text-public-muted"><span>路径：{selectedSkill.path}</span><a href={selectedSkill.source_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-bold text-public-brand hover:underline">查看 GitHub 来源 <ExternalLink className="h-3.5 w-3.5" /></a></div><button type="button" onClick={() => downloadSkill(selectedSkill)} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-public-brand px-4 py-3 text-sm font-bold text-white hover:opacity-90"><Download className="h-4 w-4" />再次下载 ZIP</button></div></div>}</div>;
}
