import { useEffect, useState } from 'react';
import { ArrowLeft, BadgeCheck, Building2, CheckCircle2, Factory, Globe2, Leaf, Loader2, LockKeyhole, MapPin, MessageSquare, PackageSearch, ShieldCheck } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { api, type PublicEnterpriseDetail } from '@/src/services/api';
import { useAuth } from '@/src/context/AuthContext';
import { PublicSiteHeader } from '@/src/components/PublicSiteHeader';

export default function FactoryDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { requestLogin } = useAuth();
  const [detail, setDetail] = useState<PublicEnterpriseDetail | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    const enterpriseId = Number(id);
    if (!Number.isInteger(enterpriseId) || enterpriseId <= 0) { setError('企业编号无效'); setLoading(false); return; }
    void api.fetchPublicEnterprise(enterpriseId).then(setDetail).catch(err => setError(err instanceof Error ? err.message : '企业信息加载失败')).finally(() => setLoading(false));
  }, [id]);

  if (loading) return <div className="public-site flex min-h-screen items-center justify-center bg-public-bg text-public-muted"><Loader2 className="mr-2 h-5 w-5 animate-spin" />正在加载工厂档案…</div>;
  if (error || !detail) return <div className="public-site min-h-screen bg-public-bg"><PublicSiteHeader onLogin={() => requestLogin('/')} /><div className="mx-auto max-w-xl px-4 py-24 text-center"><Building2 className="mx-auto h-10 w-10 text-public-muted/50" /><h1 className="mt-4 text-xl font-black">{error || '工厂不存在'}</h1><Link className="mt-5 inline-flex text-sm font-bold text-public-brand" to="/search">返回搜索</Link></div></div>;
  const factory = detail.enterprise;
  const signals = factory.public_signals;
  return <div className="public-site min-h-screen bg-public-bg text-public-text"><PublicSiteHeader onLogin={() => requestLogin(`/factory/${id}`)} /><main className="mx-auto max-w-[1180px] px-4 py-7 md:px-8 md:py-10"><button type="button" onClick={() => navigate(-1)} className="mb-6 inline-flex items-center gap-1 text-xs font-bold text-public-muted hover:text-public-brand"><ArrowLeft className="h-4 w-4" />返回上一页</button>
    <section className="rounded-2xl border border-public-border bg-white p-6 shadow-public md:p-8"><div className="flex flex-col gap-6 md:flex-row md:items-start"><div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-2xl bg-public-brand text-white"><Factory className="h-8 w-8" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-black md:text-3xl">{factory.name}</h1>{factory.business_status === '存续' && <span className="badge badge-success"><CheckCircle2 className="mr-1 inline h-3.5 w-3.5" />存续</span>}</div><p className="mt-3 flex items-center gap-1.5 text-sm text-public-muted"><MapPin className="h-4 w-4" />{factory.region} · {factory.industry_code || '制造业'}</p><p className="mt-4 max-w-3xl text-sm leading-7 text-public-muted">{factory.business_scope || '企业经营范围待补充，进入工作台后可查看更完整的企业能力资料。'}</p><div className="mt-4 flex flex-wrap gap-2">{factory.tags.map(tag => <span key={tag} className="badge badge-default">{tag}</span>)}</div></div><div className="flex shrink-0 flex-col gap-2 sm:flex-row md:flex-col"><button type="button" onClick={() => requestLogin(`/factory/${id}`)} className="btn-public-primary"><MessageSquare className="h-4 w-4" />联系 / 发起询价</button><button type="button" onClick={() => requestLogin(`/factory/${id}`)} className="btn-public-secondary"><ShieldCheck className="h-4 w-4" />收藏工厂</button></div></div><div className="mt-7 grid grid-cols-2 gap-px overflow-hidden rounded-lg border border-public-border bg-public-border md:grid-cols-4"><div className="bg-public-bg p-4"><p className="text-xs text-public-muted">信用等级</p><p className="mt-2 text-xl font-black text-public-brand">{factory.credit_level}</p></div><div className="bg-public-bg p-4"><p className="text-xs text-public-muted">注册资本</p><p className="mt-2 text-xl font-black">{factory.registered_capital ? `${factory.registered_capital.toLocaleString('zh-CN')} 万` : '未公示'}</p></div><div className="bg-public-bg p-4"><p className="text-xs text-public-muted">产能摘要</p><p className="mt-2 text-sm font-black">{factory.capacity_summary}</p></div><div className="bg-public-bg p-4"><p className="text-xs text-public-muted">数据状态</p><p className="mt-2 text-sm font-black">{signals.is_demo ? '演示数据' : '公开档案'}</p></div></div></section>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1.4fr_0.6fr]"><section className="rounded-xl border border-public-border bg-white p-6 shadow-public"><div className="flex items-center justify-between"><div><p className="eyebrow text-public-brand">Products & capability</p><h2 className="mt-1 text-xl font-black">产品与制造能力</h2></div><PackageSearch className="h-5 w-5 text-public-brand" /></div>{detail.products.length ? <div className="mt-5 grid gap-3 md:grid-cols-2">{detail.products.map(product => <article key={product.id} className="rounded-lg border border-public-border bg-public-bg p-4"><h3 className="font-bold">{product.title}</h3><p className="mt-2 text-xs leading-5 text-public-muted">{product.subtitle}</p><div className="mt-3 flex flex-wrap gap-1.5">{product.tags.map(tag => <span key={tag} className="badge badge-default">{tag}</span>)}</div></article>)}</div> : <div className="mt-5 rounded-lg bg-public-bg p-8 text-center text-sm text-public-muted">公开产品资料暂未补充</div>}</section><aside className="space-y-4"><section className="rounded-xl border border-public-border bg-white p-6 shadow-public"><h2 className="font-black">公开能力信号</h2><div className="mt-4 space-y-3 text-sm">{[[signals.is_export, Globe2, '支持出口'], [signals.is_green_factory, Leaf, '绿色工厂'], [signals.is_little_giant, BadgeCheck, '专精特新'], [signals.has_decision_maker, ShieldCheck, '有决策人联系方式']].map(([active, Icon, label]) => <div key={label as string} className="flex items-center gap-2">{active ? <Icon className="h-4 w-4 text-emerald-600" /> : <Icon className="h-4 w-4 text-public-muted/40" />}<span className={active ? 'font-semibold' : 'text-public-muted'}>{label as string}</span>{active && <CheckCircle2 className="ml-auto h-4 w-4 text-emerald-600" />}</div>)}</div></section><section className="rounded-xl border border-public-border bg-white p-6 shadow-public"><LockKeyhole className="h-5 w-5 text-public-brand" /><h2 className="mt-3 font-black">继续了解这家工厂</h2><p className="mt-2 text-xs leading-5 text-public-muted">联系方式、完整产能、历史履约和报价信息，需要企业登录后查看。</p><button type="button" onClick={() => requestLogin(`/factory/${id}`)} className="btn-public-primary mt-4 w-full">登录后联系企业</button></section></aside></div>
    <p className="mt-5 text-center text-[11px] text-public-muted">数据来源：{signals.source || '企业公开档案'} · 更新时间：{factory.data_updated_at?.slice(0, 10) || '待补充'} · {signals.is_demo ? '演示数据，仅供产品体验' : '公开数据仅作参考'}</p>
  </main></div>;
}
