import { Search, ExternalLink, Clock3, Newspaper, RefreshCw, ArrowUpRight, Factory, Globe2, Cpu, ShieldCheck, TrendingUp, Boxes } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { PublicSiteHeader } from '@/src/components/PublicSiteHeader';
import { api, type IndustryNewsItem } from '@/src/services/api';

const categories = ['全部', '政策法规', '产业趋势', '供应链', '技术创新', '企业动态', '出海与贸易'];
const dateText = (value?: string | null) => value ? new Date(value).toLocaleDateString('zh-CN') : '时间待同步';

const industryBriefs = [
  { icon: TrendingUp, category: '产业趋势', title: '制造业供应链正在从“找得到”走向“看得懂”', summary: '企业越来越关注供应商的真实产能、交付稳定性与协同效率，供应链数据透明度成为新的竞争力。', tag: '供应链可视化' },
  { icon: Cpu, category: '技术创新', title: 'AI 正在进入工厂的排产、质检与报价环节', summary: '从订单拆解到异常预警，智能工具开始帮助制造企业缩短响应链路，让经验沉淀为可复用的流程。', tag: '智能制造' },
  { icon: Boxes, category: '供应链', title: '小批量、快交付成为柔性制造的新常态', summary: '新品试制和多品种订单增长，倒逼工厂提升换线效率、物料协同和小单报价能力。', tag: '柔性生产' },
  { icon: ShieldCheck, category: '政策法规', title: '绿色工厂评价成为采购决策的重要参考', summary: '节能降碳、合规生产和可追溯能力，正在从加分项变成制造企业参与大客户供应链的基础能力。', tag: '绿色制造' },
  { icon: Globe2, category: '出海与贸易', title: '制造企业出海从单点订单转向本地化协同', summary: '海外市场的仓配、认证和售后能力逐渐成为订单落地的关键，国内供应链需要更早参与规划。', tag: '产业出海' },
  { icon: Factory, category: '企业动态', title: '专精特新企业持续补强产业链关键环节', summary: '细分领域的工艺积累和快速响应能力，为大中型企业提供了更具韧性的供应链备选。', tag: '企业能力' },
];

export default function IndustryNews() {
  const [params, setParams] = useSearchParams(); const [items, setItems] = useState<IndustryNewsItem[]>([]);
  const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const category = params.get('category') || ''; const q = params.get('q') || ''; const page = Number(params.get('page') || 1);
  const load = () => { setLoading(true); setError(''); void api.fetchIndustryNews({ category, q, page, per_page: 12 }).then((data) => { setItems(data.items); setTotal(data.total); }).catch((err) => setError(err instanceof Error ? err.message : '资讯暂时无法加载')).finally(() => setLoading(false)); };
  useEffect(load, [category, q, page]);
  const featured = items.filter((item) => item.is_featured).slice(0, 3);
  const setFilter = (key: string, value: string) => { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); next.delete('page'); setParams(next); };
  return <div className="public-site min-h-screen bg-public-bg text-public-text"><PublicSiteHeader />
    <main className="mx-auto max-w-[1240px] px-4 py-8 md:px-8 md:py-12">
      <section className="rounded-xl border border-public-border bg-white p-6 md:p-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow text-public-brand">MANUFACTURING INSIGHTS</p><h1 className="mt-2 text-3xl font-black">行业资讯</h1><p className="mt-2 text-sm text-public-muted">关注制造业政策、产业趋势与供应链动态</p></div><div className="text-right text-xs text-public-muted">内容来自白名单 RSS<br />更新时间以实际同步为准</div></div>
        <form className="mt-6 flex gap-2" onSubmit={(event) => { event.preventDefault(); setFilter('q', (event.currentTarget.elements.namedItem('q') as HTMLInputElement).value); }}><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-public-muted" /><input name="q" defaultValue={q} placeholder="搜索政策、技术、供应链关键词" className="w-full rounded-lg border border-public-border bg-public-bg py-2.5 pl-9 pr-3 text-sm outline-none focus:border-public-brand" /></div><button className="btn-public-primary" type="submit">搜索</button></form>
        <div className="mt-5 flex gap-2 overflow-x-auto pb-1">{categories.map((item) => <button key={item} type="button" onClick={() => setFilter('category', item === '全部' ? '' : item)} className={`whitespace-nowrap rounded-lg border px-3 py-2 text-xs font-bold ${((item === '全部' && !category) || item === category) ? 'border-public-brand bg-public-brand text-white' : 'border-public-border text-public-muted hover:border-public-brand hover:text-public-brand'}`}>{item}</button>)}</div>
      </section>
      {featured.length > 0 && <section className="mt-6"><div className="mb-3 flex items-center gap-2"><Newspaper className="h-4 w-4 text-public-brand" /><h2 className="font-black">推荐专题</h2></div><div className="grid gap-4 md:grid-cols-3">{featured.map((item) => <NewsCard key={item.id} item={item} featured />)}</div></section>}
      <div className="mt-7 grid gap-6 lg:grid-cols-[1fr_280px]"><section><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-black">最新资讯 <span className="ml-2 text-xs font-medium text-public-muted">共 {total} 篇</span></h2><button type="button" onClick={load} className="inline-flex items-center gap-1 text-xs font-bold text-public-muted hover:text-public-brand"><RefreshCw className="h-3.5 w-3.5" />刷新</button></div>{loading ? <State text="正在加载资讯…" /> : error ? <State text={error} action="重试" onClick={load} /> : items.length === 0 ? <State text={q || category ? '没有符合条件的资讯' : 'RSS 尚未同步，暂无文章'} /> : <div className="space-y-3">{items.map((item) => <NewsCard key={item.id} item={item} />)}</div>}{total > 12 && <div className="mt-5 flex justify-center gap-3 text-xs"><button disabled={page <= 1} onClick={() => setFilter('page', String(page - 1))} className="btn-public-secondary disabled:opacity-40">上一页</button><span className="py-2 text-public-muted">第 {page} 页</span><button disabled={page * 12 >= total} onClick={() => setFilter('page', String(page + 1))} className="btn-public-secondary disabled:opacity-40">下一页</button></div>}</section>
        <aside className="space-y-4"><div className="rounded-xl border border-public-border bg-white p-5"><h3 className="font-black">链小易快捷提问</h3><p className="mt-2 text-xs leading-6 text-public-muted">总结政策、分析影响，或根据资讯找相关工厂。</p><Link to="/aia?query=请帮我分析最新制造业资讯并找相关工厂" className="mt-3 inline-flex text-xs font-bold text-public-brand">去问链小易 →</Link></div><div className="rounded-xl border border-public-border bg-white p-5"><h3 className="font-black">找工厂</h3><p className="mt-2 text-xs leading-6 text-public-muted">从公开企业能力中筛选可核验的制造资源。</p><Link to="/search" className="mt-3 inline-flex text-xs font-bold text-public-brand">搜索工厂 →</Link></div></aside></div>
      {!q && !category && <section className="mt-9"><div className="mb-4 flex items-end justify-between"><div><div className="flex items-center gap-2"><Newspaper className="h-4 w-4 text-public-brand" /><h2 className="text-lg font-black">本周产业观察</h2></div><p className="mt-1 text-xs text-public-muted">链易配围绕制造业经营者整理的趋势速览，帮助你快速找到值得关注的方向。</p></div><Link to="/search" className="hidden items-center gap-1 text-xs font-bold text-public-brand sm:inline-flex">发现相关工厂 <ArrowUpRight className="h-3.5 w-3.5" /></Link></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{industryBriefs.map(({ icon: Icon, category: briefCategory, title, summary, tag }) => <article key={title} className="group rounded-xl border border-public-border bg-white p-5 transition hover:-translate-y-0.5 hover:border-public-brand/50 hover:shadow-public"><div className="flex items-center justify-between"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-public-brand-soft text-public-brand"><Icon className="h-4 w-4" /></span><span className="rounded-full bg-public-bg px-2.5 py-1 text-[11px] font-bold text-public-muted">{briefCategory}</span></div><h3 className="mt-4 text-base font-black leading-7 group-hover:text-public-brand">{title}</h3><p className="mt-2 line-clamp-3 text-sm leading-6 text-public-muted">{summary}</p><div className="mt-4 flex items-center justify-between border-t border-public-border pt-3 text-[11px] text-public-muted"><span>平台产业观察</span><span className="font-bold text-public-brand">#{tag}</span></div></article>)}</div></section>}
    </main></div>;
}
function NewsCard({ item, featured = false }: { item: IndustryNewsItem; featured?: boolean; key?: string | number }) { return <article className={`rounded-xl border border-public-border bg-white p-5 transition hover:border-public-brand/50 hover:shadow-public ${featured ? 'min-h-[170px]' : ''}`}><div className="flex items-center gap-2 text-[11px] text-public-muted"><span className="rounded bg-public-brand-soft px-2 py-1 font-bold text-public-brand">{item.category}</span>{item.chain_stage && <span className="rounded bg-public-bg px-2 py-1 font-semibold text-public-brand">{item.chain_stage}</span>}<span>{item.source_name}</span><span>·</span><span>{dateText(item.published_at)}</span></div><a href={item.source_url} target="_blank" rel="noopener noreferrer" className="mt-3 block text-base font-black leading-7 hover:text-public-brand">{item.title}</a><p className="mt-2 line-clamp-2 text-sm leading-6 text-public-muted">{item.summary || '暂无摘要，查看详情了解产业链关联。'}</p>{(item.related_enterprises || []).length > 0 && <p className="mt-2 text-xs font-semibold text-public-brand">关联企业：{item.related_enterprises?.map((enterprise) => enterprise.name).join('、')}</p>}<div className="mt-3 flex items-center justify-between text-[11px] text-public-muted"><span className="inline-flex items-center gap-1"><Clock3 className="h-3 w-3" />外部来源 · 抓取 {dateText(item.fetched_at)}</span><a href={item.source_url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 hover:text-public-brand">原文 <ExternalLink className="h-3 w-3" /></a></div></article>; }
function State({ text, action, onClick }: { text: string; action?: string; onClick?: () => void }) { return <div className="rounded-xl border border-dashed border-public-border bg-white px-6 py-16 text-center text-sm text-public-muted">{text}{action && <button type="button" onClick={onClick} className="ml-3 font-bold text-public-brand">{action}</button>}</div>; }
