import { ArrowLeft, ExternalLink, Sparkles } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { PublicSiteHeader } from '@/src/components/PublicSiteHeader';
import { api, type IndustryNewsItem } from '@/src/services/api';

export default function IndustryNewsDetail() {
  const { slug = '' } = useParams(); const navigate = useNavigate(); const [article, setArticle] = useState<IndustryNewsItem | null>(null); const [related, setRelated] = useState<IndustryNewsItem[]>([]); const [error, setError] = useState('');
  useEffect(() => { void api.fetchIndustryNewsDetail(slug).then((data) => { setArticle(data.article); setRelated(data.related); }).catch((err) => setError(err instanceof Error ? err.message : '资讯不存在')); }, [slug]);
  return <div className="public-site min-h-screen bg-public-bg text-public-text"><PublicSiteHeader /><main className="mx-auto max-w-[920px] px-4 py-8 md:px-8 md:py-12"><button type="button" onClick={() => navigate(-1)} className="mb-5 inline-flex items-center gap-1 text-xs font-bold text-public-muted hover:text-public-brand"><ArrowLeft className="h-4 w-4" />返回资讯</button>{error ? <div className="rounded-xl border border-public-border bg-white p-12 text-center text-sm text-public-muted">{error}</div> : !article ? <div className="rounded-xl border border-public-border bg-white p-12 text-center text-sm text-public-muted">正在加载…</div> : <><article className="rounded-xl border border-public-border bg-white p-6 md:p-10"><div className="flex flex-wrap gap-2 text-xs text-public-muted"><span className="rounded bg-public-brand-soft px-2 py-1 font-bold text-public-brand">{article.category}</span><span>{article.source_name}</span><span>· 原始发布时间 {article.published_at ? new Date(article.published_at).toLocaleString('zh-CN') : '待同步'}</span></div><h1 className="mt-5 text-2xl font-black leading-10 md:text-4xl">{article.title}</h1><p className="mt-7 border-l-4 border-public-brand bg-public-bg px-4 py-4 text-sm leading-7 text-public-text">{article.summary || '暂无摘要'}</p><div className="mt-7 text-sm leading-8 text-public-muted">{article.content_excerpt || '链易配默认仅展示 RSS 提供的摘要，不复制受版权保护的完整正文。请前往原文查看完整内容。'}</div><div className="mt-8 flex flex-wrap gap-3"><a href={article.source_url} target="_blank" rel="noopener noreferrer" className="btn-public-primary inline-flex items-center gap-2">阅读原文 <ExternalLink className="h-4 w-4" /></a><Link to={`/aia?query=${encodeURIComponent(`请帮我分析这篇资讯：${article.title}。摘要：${article.summary}`)}`} className="btn-public-secondary inline-flex items-center gap-2"><Sparkles className="h-4 w-4" />用链小易分析</Link></div><p className="mt-5 text-xs text-public-muted">外部来源：{article.source_name} · 抓取时间：{article.fetched_at ? new Date(article.fetched_at).toLocaleString('zh-CN') : '待同步'}</p></article>{related.length > 0 && <section className="mt-7"><h2 className="mb-3 font-black">相关文章</h2><div className="space-y-3">{related.map((item) => <Link key={item.id} to={`/industry-news/${item.slug}`} className="block rounded-xl border border-public-border bg-white p-4 font-bold hover:border-public-brand">{item.title}<span className="ml-3 text-xs font-normal text-public-muted">{item.category}</span></Link>)}</div></section>}</>}</main></div>;
}
