/**
 * 企业名录筛选维度（与后端 app/routes/api.py INDUSTRY_DIRECTORY_KEYWORDS 的 industry key 对齐）
 */
export const DIRECTORY_PROVINCES: { key: string; label: string }[] = [
  { key: '', label: '全部' },
  { key: '北京', label: '北京' },
  { key: '天津', label: '天津' },
  { key: '上海', label: '上海' },
  { key: '重庆', label: '重庆' },
  { key: '河北', label: '河北' },
  { key: '山西', label: '山西' },
  { key: '辽宁', label: '辽宁' },
  { key: '吉林', label: '吉林' },
  { key: '黑龙江', label: '黑龙江' },
  { key: '江苏', label: '江苏' },
  { key: '浙江', label: '浙江' },
  { key: '安徽', label: '安徽' },
  { key: '福建', label: '福建' },
  { key: '江西', label: '江西' },
  { key: '山东', label: '山东' },
  { key: '河南', label: '河南' },
  { key: '湖北', label: '湖北' },
  { key: '湖南', label: '湖南' },
  { key: '广东', label: '广东' },
  { key: '海南', label: '海南' },
  { key: '四川', label: '四川' },
  { key: '贵州', label: '贵州' },
  { key: '云南', label: '云南' },
  { key: '陕西', label: '陕西' },
  { key: '甘肃', label: '甘肃' },
  { key: '青海', label: '青海' },
  { key: '内蒙古', label: '内蒙古' },
  { key: '广西', label: '广西' },
  { key: '西藏', label: '西藏' },
  { key: '宁夏', label: '宁夏' },
  { key: '新疆', label: '新疆' },
];

export const DIRECTORY_INDUSTRIES: { key: string; label: string }[] = [
  { key: '', label: '全部' },
  { key: 'agriculture', label: '农、林、牧、渔业' },
  { key: 'mining', label: '采矿' },
  { key: 'food', label: '食品加工' },
  { key: 'textile', label: '纺织服装' },
  { key: 'wood', label: '木材 / 家具 / 造纸' },
  { key: 'chemical', label: '化工' },
  { key: 'metal', label: '金属冶炼与制品' },
  { key: 'machinery', label: '机械设备' },
  { key: 'electronics', label: '电子信息' },
  { key: 'automotive', label: '汽车及零部件' },
  { key: 'building', label: '建筑建材' },
  { key: 'electric', label: '电力电气 / 新能源' },
  { key: 'medicine', label: '医药健康' },
  { key: 'logistics', label: '物流仓储' },
  { key: 'retail', label: '批发零售 / 贸易' },
  { key: 'service', label: '软件信息 / 技术服务' },
];
